# Generated by Django 2.2.6 on 2019-10-29 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20191024_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='imprint',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
